main:
    random_seed: 0
    saved_dir: './saved/deep_avatar'

dataset:
    name: 'DeepAvatarDataset'
    kwargs:
        base_dir: '/home/tungi/datasets/mf_individuals'
        tex_size: 1024
        debug: false
            
dataloader:
    name: 'VanillaDataLoader'
    kwargs:
        train_batch_size: 4
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net:
    name: 'DeepAvatarVAE'
    kwargs:
        tex_size: 1024
        mesh_inp_size: 21918
        n_latent: 256
        res: true
        
optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0003
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 1
        gamma: 0.95

logger:
    name: 'DeepAvatarLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 4
        early_stop: 0

trainer:
    name: 'DeepAvatarTrainer'
    kwargs:
        tex_size: 1024
        resolution: [2048, 1334]
        lambda_verts: 1.0
        lambda_tex: 1.0
        lambda_screen: 1.0
        lambda_kl: 0.01 
        device: 'cuda:0'
        num_epochs: 48