main:
    random_seed: 0
    saved_dir: '/home/tungi/conferencing/saved/train'

dataset:
    name: 'DAVAE2Dataset'
    kwargs:
        base_dir: '/home/tungi/datasets/MF_davae'
        debug: false
            
dataloader:
    name: 'ImageLoader'
    kwargs:
        train_batch_size: 16
        valid_batch_size: 4
        shuffle: true
        num_workers: 8

net:
    name: 'DeepAppearanceVAE'
    kwargs:
        tex_size: 512
        
losses:
    - name: 'MeshLoss'
      weight: 1.0
    - name: 'ScreenLoss'
      weight: 1.0
    - name: 'KLLoss'
      weight: 1e-2

metrics:
    - name: 'PSNR'
    - name: 'SSIM'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 3e-4
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 1
        gamma: 0.95

logger:
    name: 'ImageLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'DAVAETrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 64