main:
    random_seed: 0
    saved_dir: './saved/ft'
    encoder_path: './saved/domain_adapt/checkpoints/model_best.pth'
    decoder_path: './saved/deep_avatar/checkpoints/model_best.pth'

dataset:
    name: 'ImageFinetuneDataset'
    kwargs:
        base_dir: '/home/tungi/datasets/mf'
        im_size: 512
        tex_size: 1024
        debug: false
            
dataloader:
    name: 'VanillaDataLoader'
    kwargs:
        train_batch_size: 4
        valid_batch_size: 1
        shuffle: true
        num_workers: 8

net: 
    name: 'DeepAppearanceModel'
    kwargs:
        im_size: 512
        tex_size: 1024
        mesh_inp_size: 21918
        n_latent: 256
        res: true
        n_cams: 42
        
optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001
        weight_decay: 0
        amsgrad: false

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 1
        gamma: 0.95

logger:
    name: 'ImageFinetuneLogger'
    kwargs:
        dummy_input: [16, 1, 128, 128]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 8
        early_stop: 0

finetuner:
    name: 'ImageFinetuner'
    kwargs:
        resolution: [2048, 1334]
        lambda_screen: 1.0
        lambda_kl: 0.01 
        device: 'cuda:0'
        num_epochs: 24